networks:
    mz:
        int: 'ffmz.org'         # internal
        srd: 'freifunk-mwu.de'  # shared
        num: 37
        lng: 'mainz'            # natural language
    wi:
        int: 'ffwi.org'         # internal
        srd: 'freifunk-mwu.de'  # shared
        num: 56
        lng: 'wiesbaden'        # natural language

openwrt:
    release_name: 'barrier_breaker'
    release_ver: '14.07'

gateways:
    5:
        name: 'hinterschinken'
        pubkey:
            mz: 'aad6b746134a657e31bc4e45154e1dcf0429e5e3b6bd6ba5ab0821c55dddb043'
            wi: 'a539f07c356f8865f4bac00150292bb067da9eba1501782a7dc86b4b3b829858'
    7:
        name: 'spinat'
        pubkey:
            mz: '9e59a202eccabe1aac37d8000e762ecb05e17b3e521f7a54ab693af66e4adfb7'
            wi: '9de492aad55c91d2871ab2d277f612eb31011eb242830e421c2e7478c1e11406'
    23:
        name: 'lotuswurzel'
        pubkey:
            mz: 'd73479cc97a87ffd4b256a873e505f3264408ed077b248358c52e8dc82bbfc07'
            wi: '45c22f99699ea2cea22eb00c024a32f4d04bbee649138a4df6ee2090e2736ca8'

formats:
    ntp:  '%d.ntp.%s'
    v4:   '10.%d.0.%d'
    v6:   'fd%d:b4dc:4b1e::a%x:%x'
    cdns: 'gate%02d.%s'
    ndns: '%s.%s'
    remote: |
        %s = {
            key = '%s',
            remotes = {'"%s" port 100%d'},
        },

site:

    # site.conf
    site_name:
        mz: 'Freifunk Mainz'
        wi: 'Freifunk Wiesbaden'
    site_code:
        mz: 'ffmz'
        wi: 'ffwi'
    ssid:
        mz: 'Freifunk Mainz'
        wi: 'wiesbaden.freifunk.net'
    mesh_ssid:
        mz: '02:04:08:16:32:64'
        wi: '64:32:16:08:04:02'
    mesh_bssid:
        mz: '02:04:08:16:32:64'
        wi: '64:32:16:08:04:02'

    descr_mailkeys:
        mz: 'keys@freifunk-mainz.de'
        wi: 'keys@freifunk-wiesbaden.de'

    descr_url:
        mz: 'freifunk-mainz.de'
        wi: 'freifunk-wiesbaden.de'

    # modules
    modules_name: 'ffmwu'
    modules_remote: 'git://github.com/freifunk-mwu/packages-ffmwu.git'
    modules_branch:
        mz: 'mz'
        wi: 'wi'
    modules_commit:
        mz: '........................................'
        wi: '........................................'

    # site.mk
    batman_pkg: 'gluon-mesh-batman-adv-15'
    gluon_release_num: '0.0.4'
    gluon_priority: '0.2'

build:
    branches: ['stable', 'beta', 'experimental']
    signkeys:
        autobuild:   '1951f045ea50ba3b839f1902ad389935256f09e589bdf8e6fd697e54143eef50'
        spky:        '3d1af00550dec5f401dbacef00d6d73947f52bf078ed6891a4cf4855e5787cf9'
        ungenannter: 'b71588aad2dde605062cf0da82cf22bb0316cbb21e87cb2e19e155fe448afa99'
        kokel:       '784249da3c254db96df556540b2c6f32e64a23269e48f03e78f61d9be2d9398f'
        knirps:      'df0373c8f9783632406e57948aac3e93efbcae737e8c3971da0bb53fcc33f649'
