networks:
    mz:
        int: 'ffmz.org'         # internal
        srd: 'freifunk-mwu.de'  # shared
        num: 37
        lng: 'mainz'            # natural language
    wi:
        int: 'ffwi.org'         # internal
        srd: 'freifunk-mwu.de'  # shared
        num: 56
        lng: 'wiesbaden'        # natural language

openwrt:
    release_name: 'chaos_calmer'
    release_ver: '15.05-rc3'

gateways:
    7:
        name: 'spinat'
        pubkey:
            mz: '9e59a202eccabe1aac37d8000e762ecb05e17b3e521f7a54ab693af66e4adfb7'
            wi: '9de492aad55c91d2871ab2d277f612eb31011eb242830e421c2e7478c1e11406'
    23:
        name: 'lotuswurzel'
        pubkey:
            mz: 'd73479cc97a87ffd4b256a873e505f3264408ed077b248358c52e8dc82bbfc07'
            wi: '45c22f99699ea2cea22eb00c024a32f4d04bbee649138a4df6ee2090e2736ca8'
    208:
        name: 'kaschu'
        pubkey:
            mz: 'e46bac7a7f4141175aea54f8c8ee0222e0f4d20cad257b56eb5eee6f139378e5'
            wi: '92802dc965cd735708c2203630d4c95232fae99beee1fcf90dfa92eeaf0b625e'
    231:
        name: 'wasserfloh'
        pubkey:
            mz: '9c00e0534a9dc5232e9bfacb304261f21f24604ad233b648bf52d6b40ca60884'
            wi: '8b35d24e192cac0c70925e5101fad7d6430726b410bc53eb581d2b03a3e3f97b'

formats:
    ntp:  '%d.ntp.%s'
    v4:   '10.%d.0.%d'
    v6:   'fd%d:b4dc:4b1e::a%x:%x'
    cdns: 'gate%02d.%s'
    ndns: '%s.%s'
    remote: |
        %s = {
            key = '%s',
            remotes = {'"%s" port 100%d'},
        },

site:

    # site.conf
    site_name:
        mz: 'Freifunk Mainz'
        wi: 'Freifunk Wiesbaden'
    site_code:
        mz: 'ffmz'
        wi: 'ffwi'
    ssid:
        mz: 'Freifunk Mainz'
        wi: 'wiesbaden.freifunk.net'
    ibss_ssid:
        mz: '02:04:08:16:32:64'
        wi: '64:32:16:08:04:02'
    ibss_bssid:
        mz: '02:04:08:16:32:64'
        wi: '64:32:16:08:04:02'
    mesh_id:
        mz: 'laeKahd4'
        wi: 'ShawXm3u'
    mcast_rate:
        mz: '12000'
        wi: '12000'

    descr_mailkeys:
        mz: 'keys@freifunk-mainz.de'
        wi: 'keys@freifunk-wiesbaden.de'

    descr_url:
        mz: 'www.freifunk-mainz.de'
        wi: 'wiesbaden.freifunk.net'

    hostname_prefix:
        mz: ''
        wi: ''

    # modules
    modules_name: 'ffmwu'
    modules_remote: 'git://github.com/freifunk-mwu/packages-ffmwu.git'
    modules_branch:
        mz: 'mz'
        wi: 'wi'
    modules_commit:
        mz: '723b82aaf70f62d795a00fa657b8f92e2346e270'
        wi: '723b82aaf70f62d795a00fa657b8f92e2346e270'

    # site.mk
    batman_pkg: 'gluon-mesh-batman-adv-15'
    gluon_release_num: '0.3'
    gluon_priority: '3.2'

build:
    branches: ['stable', 'beta', 'experimental']
    signkeys:
        autobuild:   '1951f045ea50ba3b839f1902ad389935256f09e589bdf8e6fd697e54143eef50'
        spky:        '3d1af00550dec5f401dbacef00d6d73947f52bf078ed6891a4cf4855e5787cf9'
        ungenannter: 'ae5e07dbfa418b8644e4dba637c3836ef171c8fcc0fcc7404a2487a5bbb6b556'
        kokel:       '784249da3c254db96df556540b2c6f32e64a23269e48f03e78f61d9be2d9398f'
        knirps:      'df0373c8f9783632406e57948aac3e93efbcae737e8c3971da0bb53fcc33f649'
        prisma:      'a2f42ad93a24a6e4d0063e362f343610c015cca9a07592a189edcbb098bf0e79'
        markus:      '5ae89be149319ef2caeb805e4ea1a082922cf4f71d90ab723b0119a39d8463df'
        juventas:    'b658a18fbbbdb1e5a3faf630181b7343d451d1381a994077e3d2b54134583070'
        
